PROGRAM = AlphaScanFirmware
EXTRA_COMPONENTS = $(CURRENT_RTOS)/extras/cpp_support
EXTRA_COMPONENTS += extras/dhcpserver
EXTRA_COMPONENTS += extras/rboot-ota extras/mbedtls
include $(CURRENT_RTOS)/common.mk
